#!/bin/bash
#
# DeVine Blue/Green 무중단 배포 스크립트
#
# 사용법:
#   ./deploy.sh <service> <image_tag>
#   ./deploy.sh backend abc123def
#   ./deploy.sh ai abc123def
#
set -euo pipefail

SERVICE="$1"          # "backend" 또는 "ai"
NEW_TAG="$2"          # Docker 이미지 태그 (commit SHA)
DEPLOY_DIR="$(cd "$(dirname "$0")" && pwd)"
SLOT_FILE="${DEPLOY_DIR}/.active-slot-${SERVICE}"

cd "$DEPLOY_DIR"

# ─────────────────────────────────────────────
# 1. 현재 활성 슬롯 확인
# ─────────────────────────────────────────────
if [ -f "$SLOT_FILE" ]; then
  CURRENT=$(cat "$SLOT_FILE")
else
  # 초기 상태: 실행 중인 컨테이너로 판단
  if docker ps --format '{{.Names}}' | grep -q "devine-${SERVICE}-blue"; then
    CURRENT=blue
  elif docker ps --format '{{.Names}}' | grep -q "devine-${SERVICE}-green"; then
    CURRENT=green
  else
    CURRENT=none
  fi
fi

# 다음 슬롯 결정
if [ "$CURRENT" = "blue" ]; then
  NEXT=green
else
  NEXT=blue
fi

echo "============================================"
echo "  DeVine ${SERVICE} Blue/Green Deploy"
echo "  Current: ${CURRENT} → Next: ${NEXT}"
echo "  Image tag: ${NEW_TAG}"
echo "============================================"

# ─────────────────────────────────────────────
# 2. 새 슬롯 이미지 Pull & 시작
# ─────────────────────────────────────────────
TAG_VAR="${SERVICE^^}_${NEXT^^}_TAG"  # e.g. BACKEND_GREEN_TAG
export "$TAG_VAR"="$NEW_TAG"

echo "[Step 1] Pulling new image..."
docker compose --profile "${SERVICE}-${NEXT}" pull "${SERVICE}-${NEXT}"

echo "[Step 2] Starting ${SERVICE}-${NEXT}..."
docker compose --profile "${SERVICE}-${NEXT}" up -d "${SERVICE}-${NEXT}"

# ─────────────────────────────────────────────
# 3. 헬스체크 대기
# ─────────────────────────────────────────────
CONTAINER="devine-${SERVICE}-${NEXT}"
TIMEOUT=180
INTERVAL=3

echo "[Step 3] Waiting for ${CONTAINER} to be healthy (timeout: ${TIMEOUT}s)..."

while [ $TIMEOUT -gt 0 ]; do
  STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER" 2>/dev/null || echo "starting")

  case "$STATUS" in
    healthy)
      echo "  ✓ ${CONTAINER} is healthy!"
      break
      ;;
    unhealthy)
      echo "  ✗ ${CONTAINER} is unhealthy!"
      echo ""
      echo "--- Container Logs (last 50 lines) ---"
      docker logs --tail=50 "$CONTAINER"
      echo "--------------------------------------"
      echo ""
      echo "[Rollback] Removing failed container..."
      docker compose --profile "${SERVICE}-${NEXT}" down
      exit 1
      ;;
    *)
      echo "  ... status: ${STATUS} (remaining: ${TIMEOUT}s)"
      sleep $INTERVAL
      TIMEOUT=$((TIMEOUT - INTERVAL))
      ;;
  esac
done

if [ $TIMEOUT -le 0 ]; then
  echo "  ✗ Health check timeout!"
  echo ""
  echo "--- Container Logs (last 50 lines) ---"
  docker logs --tail=50 "$CONTAINER"
  echo "--------------------------------------"
  echo ""
  echo "[Rollback] Removing timed-out container..."
  docker compose --profile "${SERVICE}-${NEXT}" down
  exit 1
fi

# ─────────────────────────────────────────────
# 4. Nginx upstream 전환 (무중단 핵심)
# ─────────────────────────────────────────────
echo "[Step 4] Switching Nginx upstream to ${SERVICE}-${NEXT}..."

# 각 서비스의 활성 슬롯 결정
if [ "$SERVICE" = "backend" ]; then
  BACKEND_ACTIVE="$NEXT"
  AI_ACTIVE=$(cat "${DEPLOY_DIR}/.active-slot-ai" 2>/dev/null || echo "blue")
else
  BACKEND_ACTIVE=$(cat "${DEPLOY_DIR}/.active-slot-backend" 2>/dev/null || echo "blue")
  AI_ACTIVE="$NEXT"
fi

# upstream.conf 재생성
cat > "${DEPLOY_DIR}/nginx/conf.d/upstream.conf" <<EOF
# Auto-generated by deploy.sh - $(date '+%Y-%m-%d %H:%M:%S')
# Active slots: backend=${BACKEND_ACTIVE}, ai=${AI_ACTIVE}

upstream backend {
    server devine-backend-${BACKEND_ACTIVE}:${SPRING_PORT:-8080};
}

upstream ai {
    server devine-ai-${AI_ACTIVE}:${FAST_PORT:-8000};
}
EOF

# Nginx 설정 검증 후 reload
if ! docker exec devine-nginx nginx -t 2>&1; then
  echo "  ✗ Nginx config test failed! Keeping current upstream."
  docker compose --profile "${SERVICE}-${NEXT}" down
  exit 1
fi

docker exec devine-nginx nginx -s reload
echo "  ✓ Nginx reloaded successfully"

# ─────────────────────────────────────────────
# 5. 활성 슬롯 기록
# ─────────────────────────────────────────────
echo "$NEXT" > "$SLOT_FILE"

# ─────────────────────────────────────────────
# 6. 기존 컨테이너 종료 (graceful)
# ─────────────────────────────────────────────
if [ "$CURRENT" != "none" ]; then
  echo "[Step 5] Waiting 10s for in-flight requests to complete..."
  sleep 10

  echo "[Step 6] Stopping old container (${SERVICE}-${CURRENT})..."
  docker compose --profile "${SERVICE}-${CURRENT}" down
  echo "  ✓ Old container stopped"
fi

# ─────────────────────────────────────────────
# 7. 이미지 정리
# ─────────────────────────────────────────────
echo "[Step 7] Cleaning up unused images..."
docker image prune -f
echo "  ✓ Cleanup done"

echo ""
echo "============================================"
echo "  Deploy complete!"
echo "  Active: ${SERVICE}-${NEXT} (tag: ${NEW_TAG})"
echo "============================================"
