#!/bin/bash
#
# DeVine Blue/Green 무중단 배포 스크립트
#
# 사용법:
#   ./deploy.sh <backend|ai> <image_tag>
#   ./deploy.sh backend abc123def
#   ./deploy.sh ai abc123def
#
set -euo pipefail

# ─── 입력 검증 ───────────────────────────────────────
SERVICE="${1:?Usage: $0 <backend|ai> <image_tag>}"
NEW_TAG="${2:?Usage: $0 <backend|ai> <image_tag>}"

if [[ "$SERVICE" != "backend" && "$SERVICE" != "ai" ]]; then
  echo "Error: SERVICE must be 'backend' or 'ai', got '${SERVICE}'"
  exit 1
fi

DEPLOY_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DEPLOY_DIR"

# ─── .env 로드 ───────────────────────────────────────
set -a; source .env; set +a
: "${SPRING_PORT:?SPRING_PORT is not set in .env}"
: "${FAST_PORT:?FAST_PORT is not set in .env}"
: "${DOCKER_USERNAME:?DOCKER_USERNAME is not set in .env}"

# ─── 슬롯 결정 ──────────────────────────────────────
SLOT_FILE=".active-slot-${SERVICE}"
CURRENT=$(cat "$SLOT_FILE" 2>/dev/null || echo "none")
NEXT=$([ "$CURRENT" = "blue" ] && echo "green" || echo "blue")

echo "============================================"
echo "  DeVine ${SERVICE} Blue/Green Deploy"
echo "  Current: ${CURRENT} → Next: ${NEXT}"
echo "  Image tag: ${NEW_TAG}"
echo "============================================"

# ─── 이미지 태그 설정 ────────────────────────────────
if   [ "$SERVICE-$NEXT" = "backend-blue"  ]; then export BACKEND_BLUE_TAG="$NEW_TAG"
elif [ "$SERVICE-$NEXT" = "backend-green" ]; then export BACKEND_GREEN_TAG="$NEW_TAG"
elif [ "$SERVICE-$NEXT" = "ai-blue"       ]; then export AI_BLUE_TAG="$NEW_TAG"
else                                               export AI_GREEN_TAG="$NEW_TAG"
fi

# ─── 새 슬롯 Pull & 시작 ─────────────────────────────
echo "[Step 1] Pulling new image..."
docker compose --profile "${SERVICE}-${NEXT}" pull "${SERVICE}-${NEXT}"

echo "[Step 2] Starting ${SERVICE}-${NEXT}..."
docker compose --profile "${SERVICE}-${NEXT}" up -d "${SERVICE}-${NEXT}"

# ─── 헬스체크 대기 ──────────────────────────────────
CONTAINER="devine-${SERVICE}-${NEXT}"
TIMEOUT=200

echo "[Step 3] Waiting for ${CONTAINER} to be healthy (timeout: ${TIMEOUT}s)..."

ELAPSED=0
while [ $ELAPSED -lt $TIMEOUT ]; do
  STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER" 2>/dev/null || echo "starting")
  case "$STATUS" in
    healthy)
      echo "  ✓ ${CONTAINER} is healthy!"
      break
      ;;
    unhealthy)
      echo "  ✗ ${CONTAINER} is unhealthy!"
      docker logs --tail=50 "$CONTAINER"
      docker stop "$CONTAINER" && docker rm -f "$CONTAINER"
      exit 1
      ;;
    *)
      echo "  ... status: ${STATUS} (${ELAPSED}/${TIMEOUT}s)"
      sleep 3
      ELAPSED=$((ELAPSED + 3))
      ;;
  esac
done

if [ $ELAPSED -ge $TIMEOUT ]; then
  echo "  ✗ Health check timeout!"
  docker logs --tail=50 "$CONTAINER"
  docker stop "$CONTAINER" && docker rm -f "$CONTAINER"
  exit 1
fi

# ─── Nginx upstream 전환 (원자적) ─────────────────────
echo "[Step 4] Switching Nginx upstream to ${SERVICE}-${NEXT}..."

BACKEND_ACTIVE=$([ "$SERVICE" = "backend" ] && echo "$NEXT" || cat ".active-slot-backend" 2>/dev/null || echo "blue")
AI_ACTIVE=$([ "$SERVICE" = "ai"           ] && echo "$NEXT" || cat ".active-slot-ai"      2>/dev/null || echo "blue")

cat > nginx/conf.d/upstream.conf.tmp <<EOF
# Auto-generated by deploy.sh - $(date '+%Y-%m-%d %H:%M:%S')
# Active slots: backend=${BACKEND_ACTIVE}, ai=${AI_ACTIVE}

set \$backend "devine-backend-${BACKEND_ACTIVE}:${SPRING_PORT}";
set \$ai      "devine-ai-${AI_ACTIVE}:${FAST_PORT}";
EOF

mv nginx/conf.d/upstream.conf nginx/conf.d/upstream.conf.bak
mv nginx/conf.d/upstream.conf.tmp nginx/conf.d/upstream.conf

if ! docker exec devine-nginx nginx -t 2>&1; then
  echo "  ✗ Nginx config test failed! Restoring previous upstream.conf..."
  mv nginx/conf.d/upstream.conf.bak nginx/conf.d/upstream.conf
  docker stop "$CONTAINER" && docker rm -f "$CONTAINER"
  exit 1
fi

docker exec devine-nginx nginx -s reload
echo "  ✓ Nginx reloaded successfully"

# ─── 활성 슬롯 기록 (Nginx reload 직후) ─────────────────
echo "$NEXT" > "$SLOT_FILE"

# ─── 구 컨테이너 종료 ────────────────────────────────
if [ "$CURRENT" != "none" ]; then
  echo "[Step 5] Waiting 10s for in-flight requests..."
  sleep 10
  echo "[Step 6] Stopping old container (${SERVICE}-${CURRENT})..."
  docker stop "devine-${SERVICE}-${CURRENT}" || true && docker rm -f "devine-${SERVICE}-${CURRENT}" || true
  echo "  ✓ Old container stopped"
fi

# ─── Dangling 이미지 정리 ─────────────────────────────
docker image prune -f --filter "dangling=true"

echo ""
echo "============================================"
echo "  Deploy complete!"
echo "  Active: ${SERVICE}-${NEXT} (tag: ${NEW_TAG})"
echo "============================================"
