# Docker 내부 DNS (컨테이너 재시작 시 IP 변경에 대응하기 위해 필수)
resolver 127.0.0.11 valid=30s;

# Backend & AI upstream definitions
upstream api {
    server api:8080;
}

upstream realtime {
    server realtime:8081;
}

# upstream ai {
#     server devine-ai:8000;
# }
